language: java
branches:
    only:
    - master
    - develop
    - fix-travis-build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  # - openjdk7 # Run in a stage after passing test with oraclejdk8
  - oraclejdk8
  # - oraclejdk9 # not passing
jobs:
  include:
    - stage: test-jdk8
      jdk: oraclejdk8
      script:
        - gradle test --info
    - stage: test-jdk7
      jdk: openjdk7
      script:
        - sudo wget "https://bouncycastle.org/download/bcprov-ext-jdk15on-158.jar" -O "${JAVA_HOME}/jre/lib/ext/bcprov-ext-jdk15on-158.jar"
        - sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security
        - echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/java-7-openjdk/security/java.security
        - gradle test --info

stages:
  - test-jdk8
  - test-jdk7

before_install:
  - echo $JAVA_HOME
  - chmod +x gradlew
#  - export JAVA_VER=$(java -version 2>&1 | sed -n ';s/.* version "\(.*\)\.\(.*\)\..*"/\1\2/p;')
#  - echo $JAVA_VER
#  - if [ $JAVA_VER = 17 ]
#  -   then
#  -     sudo wget "https://bouncycastle.org/download/bcprov-ext-jdk15on-158.jar" -O "${JAVA_HOME}/jre/lib/ext/bcprov-ext-jdk15on-158.jar"
#  - fi
#  - if [$JAVA_VER = 17]
#  -   then
#  -     sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security
#  - fi
#  - if [$JAVA_VER = 17]
#  -   then
#  -     echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/java-7-openjdk/security/java.security
#  - fi
#script:
#  - gradle test --stacktrace