language: java


# NOTE: branch 'develop' is not tested. When a deployable version is ready
# the commits must be merged into branch 'travis-ci-test' and a build will be
# triggered automatically. When the build passes, merge the new code into 'master'.
branches:
    only:
    - master
    - travis-ci-test

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: test-jdk8
      jdk: oraclejdk8
      before_install:
        - echo $JAVA_HOME
        - chmod +x gradlew
      script:
        - gradle test --info
    - stage: test-jdk7
      jdk: openjdk7
      if: branch != master
      before_install:
        - sudo wget "https://bouncycastle.org/download/bcprov-ext-jdk15on-158.jar" -O "${JAVA_HOME}/jre/lib/ext/bcprov-ext-jdk15on-158.jar"
        - sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/java-7-openjdk/security/java.security
        - echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/java-7-openjdk/security/java.security
        - echo $JAVA_HOME
        - chmod +x gradlew
      script:
        - gradle test --info
stages:
  - test-jdk8
  - test-jdk7
