package io.chino.api.permission;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.chino.api.common.ChinoApiException;
import io.chino.java.ChinoBaseAPI;
import io.chino.java.Permissions;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.IOException;
import java.util.List;

import static io.chino.java.Permissions.*;
import static io.chino.java.Permissions.ResourceType.*;

/**
 * Class that wraps an API call to Chino.io Permissions API.
 * This request can be executed using {@link Permissions#executeRequest(PermissionsRequest) Permissions.executeRequest} <br>
 *     <br>
 * Values in this class are final and <b>can not be modified</b>.
 * Use {@link Permissions#grant()} and {@link Permissions#revoke()} or a
 * {@link PermissionsRequestBuilder} to create a new instance of {@link PermissionsRequest}.<br>
 *
 */
public final class PermissionsRequest implements PermissionsContainer {
    // action info
    private final Action action;

    // subject info
    private final Subject subject;
    private final String subjectId;

    // target resource info
    private final ResourceType target;
    private final String targetId;
    private final boolean onTargetChildren;

    // permissions
    private final PermissionsRequestBuilder perms;

    // API client
    private final Permissions apiClient;

    PermissionsRequest(@NotNull PermissionsRequestBuilder builder) {
        this.action = builder.action;
        subject = builder.subject;
        subjectId = builder.subjectId;
        target = builder.target;
        targetId = builder.targetId;
        onTargetChildren = builder.onTargetChildren;
        perms = builder;

        apiClient = builder.client;
    }

    /**
     * Get a URL to the Chino.io Permissions API based on the parameters of this {@link PermissionsRequest}.
     * URLs generated by this method have to be called with a POST request, sending as the payload the {@link JsonNode}
     * returned by {@link #getBody()}
     *
     * @return The URL to execute this {@link PermissionsRequest} using Chino.io Permissions API
     */
    public String getUrlPath() {
        // Perms on top level resources
        PathBuilder path = new PathBuilder("/perms")
                .append(action.toString())
                .append(target.toString());

        if (onTargetChildren && getChildOf(target) != null) {
            // Perms on resource children
            path.append(targetId)
                .append(getChildOf(target).toString());
        } else if (targetId != null) {
            // Perms on single resource
            path.append(targetId);
        }

        // add subject information
        path.append(subject.toString())
                .append(subjectId);

        return path.toString();
    }

    /**
     * Get a {@link JsonNode} that can be used as the body of an API call to Chino.io Permissions API
     * to the URL returned by {@link #getUrlPath()}.
     *
     * @return the body of this {@link PermissionsRequest} as a {@link JsonNode}
     */
    public JsonNode getBody() {
        return new ObjectMapper().valueToTree(perms.permissions);
    }

    @Nullable
    static ResourceType getChildOf(ResourceType type) {
        switch (type) {
            case REPOSITORY:
                return SCHEMA;
            case SCHEMA:
                return DOCUMENT;
            case USER_SCHEMA:
                return USER;
            default:
                return null;
        }
    }

    /**
     * Execute this request using the {@link io.chino.java.ChinoAPI ChinoAPI} client it was created from.
     * It has the same effect as {@link Permissions#executeRequest(PermissionsRequest)}, except for the returned value.
     *
     * @return {@code true} if the outcome of the API call is successful, otherwise returns {@code false}.
     *
     * @throws IOException data processing error
     * @throws ChinoApiException server error
     */
    public boolean execute() throws IOException, ChinoApiException {
        String res = apiClient.executeRequest(this);
        return res.equals(ChinoBaseAPI.SUCCESS_MSG);
    }

    @Override
    public List<Type> getManagePermissions() {
        return perms.getManagePermissions();
    }

    @Override
    public List<Type> getAuthorizePermissions() {
        return perms.getAuthorizePermissions();
    }

    @Override
    public List<Type> getManagePermissionsOnCreatedDocuments() {
        return perms.getManagePermissionsOnCreatedDocuments();
    }

    @Override
    public List<Type> getAuthorizePermissionsOnCreatedDocuments() {
        return perms.getAuthorizePermissionsOnCreatedDocuments();
    }

    @Override
    public String toString() {
        String body = "";
        try {
            body = new ObjectMapper().writeValueAsString(getBody());
        } catch (JsonProcessingException e) {
            body = "n.a. [JsonProcessingException]:\n" + e.getMessage() + "\n\n" + e.getOriginalMessage();
        }
        return getUrlPath() + "\n\t" + body;
    }

    private class PathBuilder {
        private String path;

        public PathBuilder(String basePath) {
            path = basePath;
        }

        public PathBuilder append(String s) {
            path += "/" + s;
            return this;
        }

        @Override
        public String toString() {
            return path;
        }
    }
}
